routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('deshboard');
// });

Route::group(['namespace'=>'App\Http\Controllers'], function(){
    #backend
    Route::group(['namespace'=>'Admin','prefix' => 'admin-control','as' => 'admin.'],function(){
        // Route::get('/','LoginController@index')->name('login');
        Route::get('/','DashboardController@dashboard')->name('dashboard');
       

        Route::resources([
            'page' => 'PageController',
            'service'=> 'ServiceController',
            'product'=> 'ProductController',
            'testimonial' =>'TestimonialController',
            'contect' => 'ContectController',
            'contactde' => 'ContactdeController',
            'general' => 'GeneralController',
        ]);
    });

    Route::group(['namespace' => 'Web' ], function(){
        Route::get('/','HomeController@index')->name('home');
        Route::get('about','AboutController@about')->name('about');
        Route::get('product','ProductController@product')->name('product');
        Route::get('contact','ContactController@contact')->name('contact');
        Route::get('{page:slug}', 'PageController@show')->name('page.show');
    });
});

resources/views/backend/pages/page/create.blade.php
@extends('backend.layouts.inner')

@section('deshborad_title','Create Page')

@section('contant')

<main class="main-i">
   <div class="container-fluid">
      <div class="first-title-topadd2">

         <div class="row">
            <div class="col-lg-6">
               <div class="title-left-top-table">
                  <h4>Add page</h4>
                  <small><a href="#">Deshborad</a><i class="bx bx-caret-right"></i><span>Product</span></small>
               </div>
            </div>
            <div class="col-lg-6">
               <div class="buton-add-new">
                  <a href="{{route('admin.page.index')}}">
                     <button type="button">View</button>
                  </a>
               </div>
            </div>
         </div>
      </div>
      <div class="main-addpage-main">
          {!! Form::open(['url' => route('admin.page.store'), 'files'  => true, 'method' => 'post']) !!}
           @include('backend.pages.page.form') 
          {!! Form::close() !!}
   </div> 
</main>
@endsection

resources/views/backend/pages/page/edit.blade.php
@extends('backend.layouts.inner')

@section('deshborad_title','Edit Page')

@section('contant')

<main class="main-i">
   <div class="container-fluid">
      <div class="first-title-topadd2">

         <div class="row">
            <div class="col-lg-6">
               <div class="title-left-top-table">
                  <h4>Edit Page</h4>
                  <small><a href="#">Deshborad</a><i class="bx bx-caret-right"></i><span>Product {{ $page->title }}</span></small>
               </div>
            </div>
            <div class="col-lg-6">
               <div class="buton-add-new">
                  <a href="{{route('admin.page.index')}}">
                     <button type="button">View</button>
                  </a>
               </div>
            </div>
         </div>
      </div>
      <div class="main-addpage-main">
        
         {!! Form::open(['url' => route('admin.page.update',[$page->id]), 'files'  => true, 'method' =>'put']) !!}
            @include('backend.pages.page.form')
          {!! Form::close() !!} 
      </div>    
</main>
@endsection

resources/views/backend/pages/page/form.blade.php
<div class="row">
    <div class="col-lg-8">
        <div class="main-form-deco">
            <div class="row">
                <div class="col-lg-6">
                    <div class="formleftadd mbinput">
                        {!! Form::label('title')!!}
                        {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Enter Title']) !!}
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="formleftadd mbinput">
                        {!! Form::label('slug')!!}
                        {!! Form::text('slug', null, ['class' => 'form-control', 'placeholder' => 'Enter Slug']) !!}
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="formleftadd mbinput">
                        {!! Form::label('excerpt')!!}
                        {!! Form::textarea('excerpt', null, ['class' => 'form-control','placeholder' => 'Enter Short Description', 'rows' => '2'])!!}
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="formleftadd mbinput">
                        {!! Form::label('description')!!}
                        {!! Form::textarea('description', null, ['class' => 'form-control','placeholder' => 'Enter Description', 'rows' => '4'])!!}
                    </div>
                </div>

            </div>

        </div>
    </div>

    <div class="col-lg-4">
        @if(!empty($page->image))
        <div class="card " style="width: 18rem;">
            <img src="{{url('storage/' . $page->image)}}" class="card-img-top" alt="..." name="image">
        </div>
        @endif

        <label class="btn btn-block btn-primary mt-3">
            {{ Form::file('image', ['style' => 'display: none;']) }}
            Choose image
        </label>
    </div>
    <div class="mybutton-sub-re">
        <button type="submit" class="btn btn-primary">{{ empty($page) ? 'save' : 'update' }}</button>
        <input class="btn btn-danger" type="reset" value="Reset">
    </div>
    <div>
        <div></div>
    </div>
</div>

resources/views/backend/pages/page/index.blade.php
@extends('backend.layouts.inner')

@section('deshborad_title','view')

@section('contant')

    <main class="main-i">
        <div class="container-fluid">
            <div class="first-title-topadd">
                <div class="">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="title-left-top-table">
                            <h4>Pages / Page</h4>
                            <small><a href="#">Deshborad</a><i class='bx bx-caret-right'></i><span>Page</span></small>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="buton-add-new">
                        <a href="{{route('admin.page.create')}}">
                            <button type="button"><i class='bx bx-plus'>Add</i></button>
                        </a>
                        </div>
                    </div>
                </div>
                </div>
            </div>
            <section class="recent">
                <div class="activiti-card">
                <div class="search-top-table">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="searchbarleft">
                            <input type="text" class="search-input-table" name="Search" placeholder="Search-Filter">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="table-head-right">
                            <button type="button"><i class='bx bxs-trash'></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="table-responsiveima">
                    <table>
                        <thead class="the-colo-table">
                            <tr>
                            <th><input type="checkbox"  name="sr.no" >Sr.No</th>
                            <th>Title</th>
                            <th>Short Description</th>
                            <th>Image</th>
                            <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($pages as $index => $page)
                            <tr>
                                <td><input type="checkbox"  name="sr.no" >{{ $index + $pages->firstItem() }}.</td>
                                <td>{{ $page->title }}</td>
                                <td>{{ $page->excerpt }}</td>
                                <td>
                                <img src="{{ url('storage/' . $page->image) }}" alt="" style="width: 100px; height: 100px; object-fit: contain;">
                                </td>
                               
                            </td>
                            <td>
                                 <div class="dropdown">
                                    <div id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class='bx bx-dots-vertical-rounded'></i>
                                    </div>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                        <li><a class="dropdown-item " href="{{route('admin.page.edit',[$page->id])}}">Edit</a></li>
                                       <li> {{ Form::open(['url' => route('admin.page.destroy', [$page->id]), 'method' => 'delete']) }}
                                            <button class="dropdown-item">Delete</button>
                                            {{ Form::close() }}
                                        </li>
                                    
                                    </ul>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                {{ $pages->links("pagination::bootstrap-4") }}
                </div>
            </section>
        </div>
    </main>
@endsection